version: "3.9"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  api:
    build: .
    command: python -m uvicorn app.api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
