"""Add order table

Revision ID: 67025dcf36d9
Revises: 
Create Date: 2022-12-11 02:34:17.012247

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "67025dcf36d9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("side", sa.String(), nullable=False),
        sa.Column("instrument", sa.String(length=12), nullable=False),
        sa.Column(
            "limit_price", sa.Float(precision=2, decimal_return_scale=2), nullable=True
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
